services:
  - type: web
    name: MyPortfolio
    env: python
    plan: free
    buildCommand: |
      poetry install --no-root
    startCommand: python manage.py runserver
    envVars:
      - key: SECRET_KEY
        generateValue: true # Let Render generate a secure secret key
      - key: DEBUG
        value: 'False'
      - key: DB_NAME
        value: 'my_portfolio' # Match this with your Render PostgreSQL database name
      - key: DB_USER
        value: 'postgres' # Default user for Render PostgreSQL
      - key: DB_PASSWORD
        generateValue: true # Let Render generate a secure password
      - key: DB_HOST
        value: 'your-render-postgres-host' # Replace with Render PostgreSQL host
      - key: DB_PORT
        value: '5432' # Default port for PostgreSQL
      - key: SMTP_USERNAME
        value: 'fullstack.mohibur@gmail.com'
      - key: SMTP_PASSWORD
        value: 'mnbt rltt wsvj bfve'
      - key: CLOUDINARY_NAME
        value: 'dddt2nvvz'
      - key: CLOUDINARY_API
        value: '766673569394371'
      - key: CLOUDINARY_SECRET_KEY
        value: 'xO-46NSuWXF8Tjs6Zz0_xwRbuqI'
      - key: STRIPE_SECRET_KEY
        value: 'your_secret_key_here'
      - key: STRIPE_PUBLIC_KEY
        value: 'your_publishable_key_here'
      - key: ALLOWED_HOSTS
        value: 'localhost, .onrender.com' # Use `.onrender.com` for Render deployments
      - key: JWT_ACTIVATION_KEY
        generateValue: true # Let Render generate a secure key
      - key: JWT_ACCESS_KEY
        generateValue: true # Let Render generate a secure key
      - key: JWT_REFRESH_KEY
        generateValue: true # Let Render generate a secure key
