# Generated by Django 4.2.20 on 2025-03-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
            },
        ),
        migrations.AddField(
            model_name="contact",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
